# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  recipeappapi:
    image: recipeappapi
    build:
      context: .
      dockerfile: RecipeAppApi/Dockerfile
    ports:
      - 5095:5095
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
